# Generated by Django 3.0 on 2019-12-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id_device', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID устройства')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('lte_exists', models.BooleanField(verbose_name='Наличие LTE')),
                ('slug', models.SlugField(max_length=120, unique='name', verbose_name='URL')),
            ],
        ),
    ]
